apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim-mariadb
  labels:
     app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: storageclass-mariadb

