apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myblog-wordpress
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80