apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: certmanager
spec:
 acme:
   email: mymail
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: cert-account-key
   solvers:
     - http01:
         ingress:
           class: traefik