{
 "title": "Wordpress",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Percentage of CPU Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"wordpress\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container=\"wordpress\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    },
    { "expression": "$A/$B*100", "type": "math" },
    { "expression": "C", "reducer": "last", "type": "reduce" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         85,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "D",
     "type": "threshold"
    }
   ]
  },
  {
   "title": "Percentage of Memory Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"wordpress\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container=\"wordpress\", resource=\"memory\"})",
     "legendFormat": "__auto"
    },
    { "expression": "$A/$B*100", "reducer": "mean", "type": "math" },
    { "expression": "C", "reducer": "last", "type": "reduce" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         85,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "D",
     "type": "threshold"
    }
   ]
  },
  {
   "title": "Evolution of Percentage of CPU Usage (1 hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B*100", "type": "math" },
    { "expression": "C", "reducer": "last", "type": "reduce" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         85,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "D",
     "type": "threshold"
    }
   ]
  },
  {
   "title": "Evolution of Percentage of Memory Usage (1 hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B*100", "type": "math" }
   ]
  },
  {
   "title": "Amount of data sent and received in 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expression": "$A*1", "type": "math" },
    { "expression": "$B*1", "type": "math" }
   ]
  }
 ]
}