{
 "title": "WordPress",
 "description": "Shows some data about the WordPress database and status",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Site Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total DB size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_db_size{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Users registered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_users_total{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "User sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_user_sessions{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Posts without content",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_posts_without_content{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Posts without title",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_posts_without_title{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Options size in autoload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_options_autoload_size{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Pending Updates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wp_pending_updates{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Transient in autoload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_transient_autoload{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Options in Autoload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_options_autoload{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "wp_db_size{host=\"$host\"}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of published posts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_posts_total{host=\"$host\", status=\"published\"}"
    }
   ]
  },
  {
   "title": "Number of posts in draft",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_posts_total{host=\"$host\", status=\"draft\"}"
    }
   ]
  },
  {
   "title": "Number of pages published",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_pages_total{host=\"$host\", status=\"published\"}"
    }
   ]
  },
  {
   "title": "Number of pages in draft",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wp_pages_total{host=\"$host\", status=\"draft\"}"
    }
   ]
  }
 ]
}