prometheus:
  enabled: true
  # Other Prometheus configurations...
  prometheusSpec:
    ## Resource limits & requests
    ##
    resources:
      requests:
        memory: 400Mi

alertmanager:
  alertmanagerSpec:
    resources:
    requests:
      memory: 400Mi

grafana:
  enabled: true
  # Configures Grafana to use Loki as a datasource
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100  # Replace with your Loki service URL
      access: proxy
      isDefault: false
    # - name: MariaDB
    #   type: mysql
    #   url: jdbc:mariadb://myblog-mariadb.default.svc.cluster.local:3306/myblog-mariadb rediscluster.default.svc.cluster.local:3306
    #   access: proxy
    #   isDefault: false
    #   database: mariadb-celia
    #   user: wordpress
    #   secureJsonData:
    #     password: password
  adminPassword: admin

prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi

