prometheus:
  enabled: true
  # Other Prometheus configurations...
  prometheusSpec:
    ## Resource limits & requests
    resources:
      requests:
        memory: 200Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: default

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 200Mi

grafana:
  enabled: true
  # Configures Grafana to use mariadb as a datasource
  additionalDataSources: []
  adminPassword: mypassword
  persistence:
    enabled: true
    type: pvc
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  deploymentStrategy:
    type: Recreate
    finalizers:
    - kubernetes.io/pvc-protection  

prometheusOperator:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

