prometheus:
  enabled: true
  # Other Prometheus configurations...
  prometheusSpec:
    ## Resource limits & requests
    resources:
      requests:
        memory: 200Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: promstorage

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 200Mi

grafana:
  enabled: true
  # Configures Grafana to use mariadb as a datasource
  additionalDataSources: []
  # additionalDataSources:
  #   - name: MariaDB
  #     type: mysql
  #     url: myblog-mariadb.default.svc.cluster.local:3306
  #     access: proxy
  #     isDefault: false
  #     database: mariadb-celia
  #     user: wordpress
  #     secureJsonData:
  #       password: password
  adminPassword: mypassword
  # persistence:
  #   enabled: true
  #   storageClassName: grafstorage
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 10Gi

prometheusOperator:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

